In [1]:
# Pandas is a software library written for the Python programming language for data manipulation and analysis.
import pandas as pd
#NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
import numpy as np

In [3]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv")
df.head(10)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857
5,6,2014-01-06,Falcon 9,3325.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1005,-80.577366,28.561857
6,7,2014-04-18,Falcon 9,2296.000000,ISS,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1006,-80.577366,28.561857
7,8,2014-07-14,Falcon 9,1316.000000,LEO,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1007,-80.577366,28.561857
8,9,2014-08-05,Falcon 9,4535.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1008,-80.577366,28.561857
9,10,2014-09-07,Falcon 9,4428.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1011,-80.577366,28.561857

Identify and calculate the percentage of the missing values in each attribute

In [9]:
df.isnull().sum()/len(df)*100

FlightNumber       0.000000
Date               0.000000
BoosterVersion     0.000000
PayloadMass        0.000000
Orbit              0.000000
LaunchSite         0.000000
Outcome            0.000000
Flights            0.000000
GridFins           0.000000
Reused             0.000000
Legs               0.000000
LandingPad        28.888889
Block              0.000000
ReusedCount        0.000000
Serial             0.000000
Longitude          0.000000
Latitude           0.000000
dtype: float64

Data types

In [14]:
df.dtypes

FlightNumber        int64
Date               object
BoosterVersion     object
PayloadMass       float64
Orbit              object
LaunchSite         object
Outcome            object
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad         object
Block             float64
ReusedCount         int64
Serial             object
Longitude         float64
Latitude          float64
dtype: object

TASK 1: Calculate the number of launches on each site
The data contains several Space X launch facilities: Cape Canaveral Space Launch Complex 40 VAFB SLC 4E , Vandenberg Air Force Base Space Launch Complex 4E (SLC-4E), Kennedy Space Center Launch Complex 39A KSC LC 39A .The location of each Launch Is placed in the column LaunchSite

Next, let's see the number of launches for each site.

Use the method value_counts() on the column LaunchSite to determine the number of launches on each site:

In [23]:
df['LaunchSite'].value_counts()

CCAFS SLC 40    55
KSC LC 39A      22
VAFB SLC 4E     13
Name: LaunchSite, dtype: int64

TASK 2: Calculate the number and occurrence of each orbit
Use the method .value_counts() to determine the number and occurrence of each orbit in the column Orbit

Note: Do not count GTO, as it is a transfer orbit and not itself geostationary.

In [26]:
df['Orbit'].value_counts()

GTO      27
ISS      21
VLEO     14
PO        9
LEO       7
SSO       5
MEO       3
ES-L1     1
HEO       1
SO        1
GEO       1
Name: Orbit, dtype: int64

TASK 3: Calculate the number and occurence of mission outcome of the orbits
Use the method .value_counts() on the column Outcome to determine the number of landing_outcomes.Then assign it to a variable landing_outcomes.

In [34]:
landing_outcomes = df['Outcome'].value_counts()

In [36]:
landing_outcomes

True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: Outcome, dtype: int64

In [38]:
for i,outcome in enumerate(landing_outcomes.keys()):
    print(i,outcome)

0 True ASDS
1 None None
2 True RTLS
3 False ASDS
4 True Ocean
5 False Ocean
6 None ASDS
7 False RTLS

In [44]:
for i,outcome in enumerate(landing_outcomes):
    print(i,outcome)

0 41
1 19
2 14
3 6
4 5
5 2
6 2
7 1

In [46]:
bad_outcomes=set(landing_outcomes.keys()[[1,3,5,6,7]])
bad_outcomes

{'False ASDS', 'False Ocean', 'False RTLS', 'None ASDS', 'None None'}

TASK 4: Create a landing outcome label from Outcome column
Using the Outcome, create a list where the element is zero if the corresponding row in Outcome is in the set bad_outcome; otherwise, it's one. Then assign it to the variable landing_class:

In [54]:
landing_outcomes['landing_class'] = [0,1,0,1,0,0,0]

In [64]:
landing_outcomes.drop('landing_class', inplace = True)

In [66]:
landing_outcomes

True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: Outcome, dtype: object

In [68]:
landing_outcome_df = pd.DataFrame(landing_outcomes)

In [70]:
landing_outcome_df

            Outcome
True ASDS        41
None None        19
True RTLS        14
False ASDS        6
True Ocean        5
False Ocean       2
None ASDS         2
False RTLS        1

In [74]:
landing_outcome_df['landing_class'] = [1,0,1,0,1,0,0,0]

In [76]:
landing_outcome_df

            Outcome  landing_class
True ASDS        41              1
None None        19              0
True RTLS        14              1
False ASDS        6              0
True Ocean        5              1
False Ocean       2              0
None ASDS         2              0
False RTLS        1              0

In [80]:
landing_outcome_df.landing_class.head(5)

True ASDS     1
None None     0
True RTLS     1
False ASDS    0
True Ocean    1
Name: landing_class, dtype: int64

In [82]:
landing_outcomes.keys() = bad_outcomes

In [84]:
landing_outcomes

True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: Outcome, dtype: object

In [86]:
bad_outcomes

{'False ASDS', 'False Ocean', 'False RTLS', 'None ASDS', 'None None'}

In [106]:
landing_outcome_df['classes'] = landing_outcome_df.index.to_series().str.contains('True').astype(int)

In [96]:
landing_outcome_df.index

Index(['True ASDS', 'None None', 'True RTLS', 'False ASDS', 'True Ocean',
       'False Ocean', 'None ASDS', 'False RTLS'],
      dtype='object')

In [108]:
landing_outcome_df

            Outcome  landing_class  classes
True ASDS        41              1        1
None None        19              0        0
True RTLS        14              1        1
False ASDS        6              0        0
True Ocean        5              1        1
False Ocean       2              0        0
None ASDS         2              0        0
False RTLS        1              0        0

In [118]:
landing_outcome_df.sum('Outcome'*'classes')/landing_outcome_df.sum('Outcome')

TypeError: can't multiply sequence by non-int of type 'str'

In [112]:
landing_outcome_df.to_csv("dataset_wrangling.csv", index=False)

In [114]:
df.groupby("Orbit")["Outcome"].value_counts()

Orbit  Outcome
ES-L1  True Ocean      1
GEO    True ASDS       1
GTO    True ASDS      13
       None None      11
       False ASDS      1
       None ASDS       1
       True Ocean      1
HEO    True ASDS       1
ISS    True RTLS       7
       True ASDS       5
       None None       3
       False ASDS      2
       False Ocean     1
       False RTLS      1
       None ASDS       1
       True Ocean      1
LEO    True RTLS       4
       None None       2
       True Ocean      1
MEO    True ASDS       2
       None None       1
PO     True ASDS       5
       False ASDS      1
       False Ocean     1
       None None       1
       True Ocean      1
SO     None None       1
SSO    True RTLS       3
       True ASDS       2
VLEO   True ASDS      12
       False ASDS      2
Name: Outcome, dtype: int64

In [116]:
landing_outcome_df.Outcome.mean()

11.25

In [120]:
success_rate = (landing_outcome_df["Outcome"] * landing_outcome_df["classes"]).sum() / landing_outcome_df["Outcome"].sum()

In [122]:
success_rate

0.6666666666666666